spring:
  application:
    name: eureka-server
  redis:
    host: 192.168.10.100
    port: 6379
server:
  port: 8761
eureka:
  client:
    serviceUrl:
      defaultZone: http://discUser:discPassword@localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false